// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DataServer.proto

#ifndef PROTOBUF_DataServer_2eproto__INCLUDED
#define PROTOBUF_DataServer_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2004000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2004001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_message_reflection.h>
#include "RoleData.pb.h"
// @@protoc_insertion_point(includes)

namespace gtod {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_DataServer_2eproto();
void protobuf_AssignDesc_DataServer_2eproto();
void protobuf_ShutdownFile_DataServer_2eproto();

class SRequestCreateRole;
class SResponseCreateRole;
class SRequestRoleData;
class SResponseRoleData;
class SRequestSaveRoleData;
class SResponseSaveRoleData;
class SRequestRoleDataVersion;
class SResponseRoleDataVersion;

// ===================================================================

class SRequestCreateRole : public ::google::protobuf::Message {
 public:
  SRequestCreateRole();
  virtual ~SRequestCreateRole();
  
  SRequestCreateRole(const SRequestCreateRole& from);
  
  inline SRequestCreateRole& operator=(const SRequestCreateRole& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const SRequestCreateRole& default_instance();
  
  void Swap(SRequestCreateRole* other);
  
  // implements Message ----------------------------------------------
  
  SRequestCreateRole* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const SRequestCreateRole& from);
  void MergeFrom(const SRequestCreateRole& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // optional string ptName = 1;
  inline bool has_ptname() const;
  inline void clear_ptname();
  static const int kPtNameFieldNumber = 1;
  inline const ::std::string& ptname() const;
  inline void set_ptname(const ::std::string& value);
  inline void set_ptname(const char* value);
  inline void set_ptname(const char* value, size_t size);
  inline ::std::string* mutable_ptname();
  inline ::std::string* release_ptname();
  
  // optional string roleName = 2;
  inline bool has_rolename() const;
  inline void clear_rolename();
  static const int kRoleNameFieldNumber = 2;
  inline const ::std::string& rolename() const;
  inline void set_rolename(const ::std::string& value);
  inline void set_rolename(const char* value);
  inline void set_rolename(const char* value, size_t size);
  inline ::std::string* mutable_rolename();
  inline ::std::string* release_rolename();
  
  // @@protoc_insertion_point(class_scope:gtod.SRequestCreateRole)
 private:
  inline void set_has_ptname();
  inline void clear_has_ptname();
  inline void set_has_rolename();
  inline void clear_has_rolename();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::std::string* ptname_;
  ::std::string* rolename_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];
  
  friend void  protobuf_AddDesc_DataServer_2eproto();
  friend void protobuf_AssignDesc_DataServer_2eproto();
  friend void protobuf_ShutdownFile_DataServer_2eproto();
  
  void InitAsDefaultInstance();
  static SRequestCreateRole* default_instance_;
};
// -------------------------------------------------------------------

class SResponseCreateRole : public ::google::protobuf::Message {
 public:
  SResponseCreateRole();
  virtual ~SResponseCreateRole();
  
  SResponseCreateRole(const SResponseCreateRole& from);
  
  inline SResponseCreateRole& operator=(const SResponseCreateRole& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const SResponseCreateRole& default_instance();
  
  void Swap(SResponseCreateRole* other);
  
  // implements Message ----------------------------------------------
  
  SResponseCreateRole* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const SResponseCreateRole& from);
  void MergeFrom(const SResponseCreateRole& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // optional string ptName = 1;
  inline bool has_ptname() const;
  inline void clear_ptname();
  static const int kPtNameFieldNumber = 1;
  inline const ::std::string& ptname() const;
  inline void set_ptname(const ::std::string& value);
  inline void set_ptname(const char* value);
  inline void set_ptname(const char* value, size_t size);
  inline ::std::string* mutable_ptname();
  inline ::std::string* release_ptname();
  
  // optional uint32 errCode = 2;
  inline bool has_errcode() const;
  inline void clear_errcode();
  static const int kErrCodeFieldNumber = 2;
  inline ::google::protobuf::uint32 errcode() const;
  inline void set_errcode(::google::protobuf::uint32 value);
  
  // @@protoc_insertion_point(class_scope:gtod.SResponseCreateRole)
 private:
  inline void set_has_ptname();
  inline void clear_has_ptname();
  inline void set_has_errcode();
  inline void clear_has_errcode();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::std::string* ptname_;
  ::google::protobuf::uint32 errcode_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];
  
  friend void  protobuf_AddDesc_DataServer_2eproto();
  friend void protobuf_AssignDesc_DataServer_2eproto();
  friend void protobuf_ShutdownFile_DataServer_2eproto();
  
  void InitAsDefaultInstance();
  static SResponseCreateRole* default_instance_;
};
// -------------------------------------------------------------------

class SRequestRoleData : public ::google::protobuf::Message {
 public:
  SRequestRoleData();
  virtual ~SRequestRoleData();
  
  SRequestRoleData(const SRequestRoleData& from);
  
  inline SRequestRoleData& operator=(const SRequestRoleData& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const SRequestRoleData& default_instance();
  
  void Swap(SRequestRoleData* other);
  
  // implements Message ----------------------------------------------
  
  SRequestRoleData* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const SRequestRoleData& from);
  void MergeFrom(const SRequestRoleData& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // optional string ptName = 1;
  inline bool has_ptname() const;
  inline void clear_ptname();
  static const int kPtNameFieldNumber = 1;
  inline const ::std::string& ptname() const;
  inline void set_ptname(const ::std::string& value);
  inline void set_ptname(const char* value);
  inline void set_ptname(const char* value, size_t size);
  inline ::std::string* mutable_ptname();
  inline ::std::string* release_ptname();
  
  // @@protoc_insertion_point(class_scope:gtod.SRequestRoleData)
 private:
  inline void set_has_ptname();
  inline void clear_has_ptname();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::std::string* ptname_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];
  
  friend void  protobuf_AddDesc_DataServer_2eproto();
  friend void protobuf_AssignDesc_DataServer_2eproto();
  friend void protobuf_ShutdownFile_DataServer_2eproto();
  
  void InitAsDefaultInstance();
  static SRequestRoleData* default_instance_;
};
// -------------------------------------------------------------------

class SResponseRoleData : public ::google::protobuf::Message {
 public:
  SResponseRoleData();
  virtual ~SResponseRoleData();
  
  SResponseRoleData(const SResponseRoleData& from);
  
  inline SResponseRoleData& operator=(const SResponseRoleData& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const SResponseRoleData& default_instance();
  
  void Swap(SResponseRoleData* other);
  
  // implements Message ----------------------------------------------
  
  SResponseRoleData* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const SResponseRoleData& from);
  void MergeFrom(const SResponseRoleData& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // optional uint32 errCode = 1;
  inline bool has_errcode() const;
  inline void clear_errcode();
  static const int kErrCodeFieldNumber = 1;
  inline ::google::protobuf::uint32 errcode() const;
  inline void set_errcode(::google::protobuf::uint32 value);
  
  // optional .roledata.PBRoleTotalInfo roleData = 2;
  inline bool has_roledata() const;
  inline void clear_roledata();
  static const int kRoleDataFieldNumber = 2;
  inline const ::roledata::PBRoleTotalInfo& roledata() const;
  inline ::roledata::PBRoleTotalInfo* mutable_roledata();
  inline ::roledata::PBRoleTotalInfo* release_roledata();
  
  // @@protoc_insertion_point(class_scope:gtod.SResponseRoleData)
 private:
  inline void set_has_errcode();
  inline void clear_has_errcode();
  inline void set_has_roledata();
  inline void clear_has_roledata();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::roledata::PBRoleTotalInfo* roledata_;
  ::google::protobuf::uint32 errcode_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];
  
  friend void  protobuf_AddDesc_DataServer_2eproto();
  friend void protobuf_AssignDesc_DataServer_2eproto();
  friend void protobuf_ShutdownFile_DataServer_2eproto();
  
  void InitAsDefaultInstance();
  static SResponseRoleData* default_instance_;
};
// -------------------------------------------------------------------

class SRequestSaveRoleData : public ::google::protobuf::Message {
 public:
  SRequestSaveRoleData();
  virtual ~SRequestSaveRoleData();
  
  SRequestSaveRoleData(const SRequestSaveRoleData& from);
  
  inline SRequestSaveRoleData& operator=(const SRequestSaveRoleData& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const SRequestSaveRoleData& default_instance();
  
  void Swap(SRequestSaveRoleData* other);
  
  // implements Message ----------------------------------------------
  
  SRequestSaveRoleData* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const SRequestSaveRoleData& from);
  void MergeFrom(const SRequestSaveRoleData& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // optional string ptName = 1;
  inline bool has_ptname() const;
  inline void clear_ptname();
  static const int kPtNameFieldNumber = 1;
  inline const ::std::string& ptname() const;
  inline void set_ptname(const ::std::string& value);
  inline void set_ptname(const char* value);
  inline void set_ptname(const char* value, size_t size);
  inline ::std::string* mutable_ptname();
  inline ::std::string* release_ptname();
  
  // optional .roledata.PBRoleTotalInfo roleData = 2;
  inline bool has_roledata() const;
  inline void clear_roledata();
  static const int kRoleDataFieldNumber = 2;
  inline const ::roledata::PBRoleTotalInfo& roledata() const;
  inline ::roledata::PBRoleTotalInfo* mutable_roledata();
  inline ::roledata::PBRoleTotalInfo* release_roledata();
  
  // @@protoc_insertion_point(class_scope:gtod.SRequestSaveRoleData)
 private:
  inline void set_has_ptname();
  inline void clear_has_ptname();
  inline void set_has_roledata();
  inline void clear_has_roledata();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::std::string* ptname_;
  ::roledata::PBRoleTotalInfo* roledata_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];
  
  friend void  protobuf_AddDesc_DataServer_2eproto();
  friend void protobuf_AssignDesc_DataServer_2eproto();
  friend void protobuf_ShutdownFile_DataServer_2eproto();
  
  void InitAsDefaultInstance();
  static SRequestSaveRoleData* default_instance_;
};
// -------------------------------------------------------------------

class SResponseSaveRoleData : public ::google::protobuf::Message {
 public:
  SResponseSaveRoleData();
  virtual ~SResponseSaveRoleData();
  
  SResponseSaveRoleData(const SResponseSaveRoleData& from);
  
  inline SResponseSaveRoleData& operator=(const SResponseSaveRoleData& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const SResponseSaveRoleData& default_instance();
  
  void Swap(SResponseSaveRoleData* other);
  
  // implements Message ----------------------------------------------
  
  SResponseSaveRoleData* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const SResponseSaveRoleData& from);
  void MergeFrom(const SResponseSaveRoleData& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // optional string ptName = 1;
  inline bool has_ptname() const;
  inline void clear_ptname();
  static const int kPtNameFieldNumber = 1;
  inline const ::std::string& ptname() const;
  inline void set_ptname(const ::std::string& value);
  inline void set_ptname(const char* value);
  inline void set_ptname(const char* value, size_t size);
  inline ::std::string* mutable_ptname();
  inline ::std::string* release_ptname();
  
  // optional uint32 errCode = 2;
  inline bool has_errcode() const;
  inline void clear_errcode();
  static const int kErrCodeFieldNumber = 2;
  inline ::google::protobuf::uint32 errcode() const;
  inline void set_errcode(::google::protobuf::uint32 value);
  
  // @@protoc_insertion_point(class_scope:gtod.SResponseSaveRoleData)
 private:
  inline void set_has_ptname();
  inline void clear_has_ptname();
  inline void set_has_errcode();
  inline void clear_has_errcode();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::std::string* ptname_;
  ::google::protobuf::uint32 errcode_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];
  
  friend void  protobuf_AddDesc_DataServer_2eproto();
  friend void protobuf_AssignDesc_DataServer_2eproto();
  friend void protobuf_ShutdownFile_DataServer_2eproto();
  
  void InitAsDefaultInstance();
  static SResponseSaveRoleData* default_instance_;
};
// -------------------------------------------------------------------

class SRequestRoleDataVersion : public ::google::protobuf::Message {
 public:
  SRequestRoleDataVersion();
  virtual ~SRequestRoleDataVersion();
  
  SRequestRoleDataVersion(const SRequestRoleDataVersion& from);
  
  inline SRequestRoleDataVersion& operator=(const SRequestRoleDataVersion& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const SRequestRoleDataVersion& default_instance();
  
  void Swap(SRequestRoleDataVersion* other);
  
  // implements Message ----------------------------------------------
  
  SRequestRoleDataVersion* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const SRequestRoleDataVersion& from);
  void MergeFrom(const SRequestRoleDataVersion& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // optional string ptName = 1;
  inline bool has_ptname() const;
  inline void clear_ptname();
  static const int kPtNameFieldNumber = 1;
  inline const ::std::string& ptname() const;
  inline void set_ptname(const ::std::string& value);
  inline void set_ptname(const char* value);
  inline void set_ptname(const char* value, size_t size);
  inline ::std::string* mutable_ptname();
  inline ::std::string* release_ptname();
  
  // @@protoc_insertion_point(class_scope:gtod.SRequestRoleDataVersion)
 private:
  inline void set_has_ptname();
  inline void clear_has_ptname();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::std::string* ptname_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];
  
  friend void  protobuf_AddDesc_DataServer_2eproto();
  friend void protobuf_AssignDesc_DataServer_2eproto();
  friend void protobuf_ShutdownFile_DataServer_2eproto();
  
  void InitAsDefaultInstance();
  static SRequestRoleDataVersion* default_instance_;
};
// -------------------------------------------------------------------

class SResponseRoleDataVersion : public ::google::protobuf::Message {
 public:
  SResponseRoleDataVersion();
  virtual ~SResponseRoleDataVersion();
  
  SResponseRoleDataVersion(const SResponseRoleDataVersion& from);
  
  inline SResponseRoleDataVersion& operator=(const SResponseRoleDataVersion& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const SResponseRoleDataVersion& default_instance();
  
  void Swap(SResponseRoleDataVersion* other);
  
  // implements Message ----------------------------------------------
  
  SResponseRoleDataVersion* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const SResponseRoleDataVersion& from);
  void MergeFrom(const SResponseRoleDataVersion& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // optional string ptName = 1;
  inline bool has_ptname() const;
  inline void clear_ptname();
  static const int kPtNameFieldNumber = 1;
  inline const ::std::string& ptname() const;
  inline void set_ptname(const ::std::string& value);
  inline void set_ptname(const char* value);
  inline void set_ptname(const char* value, size_t size);
  inline ::std::string* mutable_ptname();
  inline ::std::string* release_ptname();
  
  // optional uint32 dataVersion = 2;
  inline bool has_dataversion() const;
  inline void clear_dataversion();
  static const int kDataVersionFieldNumber = 2;
  inline ::google::protobuf::uint32 dataversion() const;
  inline void set_dataversion(::google::protobuf::uint32 value);
  
  // optional uint32 errCode = 3;
  inline bool has_errcode() const;
  inline void clear_errcode();
  static const int kErrCodeFieldNumber = 3;
  inline ::google::protobuf::uint32 errcode() const;
  inline void set_errcode(::google::protobuf::uint32 value);
  
  // @@protoc_insertion_point(class_scope:gtod.SResponseRoleDataVersion)
 private:
  inline void set_has_ptname();
  inline void clear_has_ptname();
  inline void set_has_dataversion();
  inline void clear_has_dataversion();
  inline void set_has_errcode();
  inline void clear_has_errcode();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::std::string* ptname_;
  ::google::protobuf::uint32 dataversion_;
  ::google::protobuf::uint32 errcode_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(3 + 31) / 32];
  
  friend void  protobuf_AddDesc_DataServer_2eproto();
  friend void protobuf_AssignDesc_DataServer_2eproto();
  friend void protobuf_ShutdownFile_DataServer_2eproto();
  
  void InitAsDefaultInstance();
  static SResponseRoleDataVersion* default_instance_;
};
// ===================================================================


// ===================================================================

// SRequestCreateRole

// optional string ptName = 1;
inline bool SRequestCreateRole::has_ptname() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void SRequestCreateRole::set_has_ptname() {
  _has_bits_[0] |= 0x00000001u;
}
inline void SRequestCreateRole::clear_has_ptname() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void SRequestCreateRole::clear_ptname() {
  if (ptname_ != &::google::protobuf::internal::kEmptyString) {
    ptname_->clear();
  }
  clear_has_ptname();
}
inline const ::std::string& SRequestCreateRole::ptname() const {
  return *ptname_;
}
inline void SRequestCreateRole::set_ptname(const ::std::string& value) {
  set_has_ptname();
  if (ptname_ == &::google::protobuf::internal::kEmptyString) {
    ptname_ = new ::std::string;
  }
  ptname_->assign(value);
}
inline void SRequestCreateRole::set_ptname(const char* value) {
  set_has_ptname();
  if (ptname_ == &::google::protobuf::internal::kEmptyString) {
    ptname_ = new ::std::string;
  }
  ptname_->assign(value);
}
inline void SRequestCreateRole::set_ptname(const char* value, size_t size) {
  set_has_ptname();
  if (ptname_ == &::google::protobuf::internal::kEmptyString) {
    ptname_ = new ::std::string;
  }
  ptname_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* SRequestCreateRole::mutable_ptname() {
  set_has_ptname();
  if (ptname_ == &::google::protobuf::internal::kEmptyString) {
    ptname_ = new ::std::string;
  }
  return ptname_;
}
inline ::std::string* SRequestCreateRole::release_ptname() {
  clear_has_ptname();
  if (ptname_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = ptname_;
    ptname_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}

// optional string roleName = 2;
inline bool SRequestCreateRole::has_rolename() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void SRequestCreateRole::set_has_rolename() {
  _has_bits_[0] |= 0x00000002u;
}
inline void SRequestCreateRole::clear_has_rolename() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void SRequestCreateRole::clear_rolename() {
  if (rolename_ != &::google::protobuf::internal::kEmptyString) {
    rolename_->clear();
  }
  clear_has_rolename();
}
inline const ::std::string& SRequestCreateRole::rolename() const {
  return *rolename_;
}
inline void SRequestCreateRole::set_rolename(const ::std::string& value) {
  set_has_rolename();
  if (rolename_ == &::google::protobuf::internal::kEmptyString) {
    rolename_ = new ::std::string;
  }
  rolename_->assign(value);
}
inline void SRequestCreateRole::set_rolename(const char* value) {
  set_has_rolename();
  if (rolename_ == &::google::protobuf::internal::kEmptyString) {
    rolename_ = new ::std::string;
  }
  rolename_->assign(value);
}
inline void SRequestCreateRole::set_rolename(const char* value, size_t size) {
  set_has_rolename();
  if (rolename_ == &::google::protobuf::internal::kEmptyString) {
    rolename_ = new ::std::string;
  }
  rolename_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* SRequestCreateRole::mutable_rolename() {
  set_has_rolename();
  if (rolename_ == &::google::protobuf::internal::kEmptyString) {
    rolename_ = new ::std::string;
  }
  return rolename_;
}
inline ::std::string* SRequestCreateRole::release_rolename() {
  clear_has_rolename();
  if (rolename_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = rolename_;
    rolename_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}

// -------------------------------------------------------------------

// SResponseCreateRole

// optional string ptName = 1;
inline bool SResponseCreateRole::has_ptname() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void SResponseCreateRole::set_has_ptname() {
  _has_bits_[0] |= 0x00000001u;
}
inline void SResponseCreateRole::clear_has_ptname() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void SResponseCreateRole::clear_ptname() {
  if (ptname_ != &::google::protobuf::internal::kEmptyString) {
    ptname_->clear();
  }
  clear_has_ptname();
}
inline const ::std::string& SResponseCreateRole::ptname() const {
  return *ptname_;
}
inline void SResponseCreateRole::set_ptname(const ::std::string& value) {
  set_has_ptname();
  if (ptname_ == &::google::protobuf::internal::kEmptyString) {
    ptname_ = new ::std::string;
  }
  ptname_->assign(value);
}
inline void SResponseCreateRole::set_ptname(const char* value) {
  set_has_ptname();
  if (ptname_ == &::google::protobuf::internal::kEmptyString) {
    ptname_ = new ::std::string;
  }
  ptname_->assign(value);
}
inline void SResponseCreateRole::set_ptname(const char* value, size_t size) {
  set_has_ptname();
  if (ptname_ == &::google::protobuf::internal::kEmptyString) {
    ptname_ = new ::std::string;
  }
  ptname_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* SResponseCreateRole::mutable_ptname() {
  set_has_ptname();
  if (ptname_ == &::google::protobuf::internal::kEmptyString) {
    ptname_ = new ::std::string;
  }
  return ptname_;
}
inline ::std::string* SResponseCreateRole::release_ptname() {
  clear_has_ptname();
  if (ptname_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = ptname_;
    ptname_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}

// optional uint32 errCode = 2;
inline bool SResponseCreateRole::has_errcode() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void SResponseCreateRole::set_has_errcode() {
  _has_bits_[0] |= 0x00000002u;
}
inline void SResponseCreateRole::clear_has_errcode() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void SResponseCreateRole::clear_errcode() {
  errcode_ = 0u;
  clear_has_errcode();
}
inline ::google::protobuf::uint32 SResponseCreateRole::errcode() const {
  return errcode_;
}
inline void SResponseCreateRole::set_errcode(::google::protobuf::uint32 value) {
  set_has_errcode();
  errcode_ = value;
}

// -------------------------------------------------------------------

// SRequestRoleData

// optional string ptName = 1;
inline bool SRequestRoleData::has_ptname() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void SRequestRoleData::set_has_ptname() {
  _has_bits_[0] |= 0x00000001u;
}
inline void SRequestRoleData::clear_has_ptname() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void SRequestRoleData::clear_ptname() {
  if (ptname_ != &::google::protobuf::internal::kEmptyString) {
    ptname_->clear();
  }
  clear_has_ptname();
}
inline const ::std::string& SRequestRoleData::ptname() const {
  return *ptname_;
}
inline void SRequestRoleData::set_ptname(const ::std::string& value) {
  set_has_ptname();
  if (ptname_ == &::google::protobuf::internal::kEmptyString) {
    ptname_ = new ::std::string;
  }
  ptname_->assign(value);
}
inline void SRequestRoleData::set_ptname(const char* value) {
  set_has_ptname();
  if (ptname_ == &::google::protobuf::internal::kEmptyString) {
    ptname_ = new ::std::string;
  }
  ptname_->assign(value);
}
inline void SRequestRoleData::set_ptname(const char* value, size_t size) {
  set_has_ptname();
  if (ptname_ == &::google::protobuf::internal::kEmptyString) {
    ptname_ = new ::std::string;
  }
  ptname_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* SRequestRoleData::mutable_ptname() {
  set_has_ptname();
  if (ptname_ == &::google::protobuf::internal::kEmptyString) {
    ptname_ = new ::std::string;
  }
  return ptname_;
}
inline ::std::string* SRequestRoleData::release_ptname() {
  clear_has_ptname();
  if (ptname_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = ptname_;
    ptname_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}

// -------------------------------------------------------------------

// SResponseRoleData

// optional uint32 errCode = 1;
inline bool SResponseRoleData::has_errcode() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void SResponseRoleData::set_has_errcode() {
  _has_bits_[0] |= 0x00000001u;
}
inline void SResponseRoleData::clear_has_errcode() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void SResponseRoleData::clear_errcode() {
  errcode_ = 0u;
  clear_has_errcode();
}
inline ::google::protobuf::uint32 SResponseRoleData::errcode() const {
  return errcode_;
}
inline void SResponseRoleData::set_errcode(::google::protobuf::uint32 value) {
  set_has_errcode();
  errcode_ = value;
}

// optional .roledata.PBRoleTotalInfo roleData = 2;
inline bool SResponseRoleData::has_roledata() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void SResponseRoleData::set_has_roledata() {
  _has_bits_[0] |= 0x00000002u;
}
inline void SResponseRoleData::clear_has_roledata() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void SResponseRoleData::clear_roledata() {
  if (roledata_ != NULL) roledata_->::roledata::PBRoleTotalInfo::Clear();
  clear_has_roledata();
}
inline const ::roledata::PBRoleTotalInfo& SResponseRoleData::roledata() const {
  return roledata_ != NULL ? *roledata_ : *default_instance_->roledata_;
}
inline ::roledata::PBRoleTotalInfo* SResponseRoleData::mutable_roledata() {
  set_has_roledata();
  if (roledata_ == NULL) roledata_ = new ::roledata::PBRoleTotalInfo;
  return roledata_;
}
inline ::roledata::PBRoleTotalInfo* SResponseRoleData::release_roledata() {
  clear_has_roledata();
  ::roledata::PBRoleTotalInfo* temp = roledata_;
  roledata_ = NULL;
  return temp;
}

// -------------------------------------------------------------------

// SRequestSaveRoleData

// optional string ptName = 1;
inline bool SRequestSaveRoleData::has_ptname() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void SRequestSaveRoleData::set_has_ptname() {
  _has_bits_[0] |= 0x00000001u;
}
inline void SRequestSaveRoleData::clear_has_ptname() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void SRequestSaveRoleData::clear_ptname() {
  if (ptname_ != &::google::protobuf::internal::kEmptyString) {
    ptname_->clear();
  }
  clear_has_ptname();
}
inline const ::std::string& SRequestSaveRoleData::ptname() const {
  return *ptname_;
}
inline void SRequestSaveRoleData::set_ptname(const ::std::string& value) {
  set_has_ptname();
  if (ptname_ == &::google::protobuf::internal::kEmptyString) {
    ptname_ = new ::std::string;
  }
  ptname_->assign(value);
}
inline void SRequestSaveRoleData::set_ptname(const char* value) {
  set_has_ptname();
  if (ptname_ == &::google::protobuf::internal::kEmptyString) {
    ptname_ = new ::std::string;
  }
  ptname_->assign(value);
}
inline void SRequestSaveRoleData::set_ptname(const char* value, size_t size) {
  set_has_ptname();
  if (ptname_ == &::google::protobuf::internal::kEmptyString) {
    ptname_ = new ::std::string;
  }
  ptname_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* SRequestSaveRoleData::mutable_ptname() {
  set_has_ptname();
  if (ptname_ == &::google::protobuf::internal::kEmptyString) {
    ptname_ = new ::std::string;
  }
  return ptname_;
}
inline ::std::string* SRequestSaveRoleData::release_ptname() {
  clear_has_ptname();
  if (ptname_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = ptname_;
    ptname_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}

// optional .roledata.PBRoleTotalInfo roleData = 2;
inline bool SRequestSaveRoleData::has_roledata() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void SRequestSaveRoleData::set_has_roledata() {
  _has_bits_[0] |= 0x00000002u;
}
inline void SRequestSaveRoleData::clear_has_roledata() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void SRequestSaveRoleData::clear_roledata() {
  if (roledata_ != NULL) roledata_->::roledata::PBRoleTotalInfo::Clear();
  clear_has_roledata();
}
inline const ::roledata::PBRoleTotalInfo& SRequestSaveRoleData::roledata() const {
  return roledata_ != NULL ? *roledata_ : *default_instance_->roledata_;
}
inline ::roledata::PBRoleTotalInfo* SRequestSaveRoleData::mutable_roledata() {
  set_has_roledata();
  if (roledata_ == NULL) roledata_ = new ::roledata::PBRoleTotalInfo;
  return roledata_;
}
inline ::roledata::PBRoleTotalInfo* SRequestSaveRoleData::release_roledata() {
  clear_has_roledata();
  ::roledata::PBRoleTotalInfo* temp = roledata_;
  roledata_ = NULL;
  return temp;
}

// -------------------------------------------------------------------

// SResponseSaveRoleData

// optional string ptName = 1;
inline bool SResponseSaveRoleData::has_ptname() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void SResponseSaveRoleData::set_has_ptname() {
  _has_bits_[0] |= 0x00000001u;
}
inline void SResponseSaveRoleData::clear_has_ptname() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void SResponseSaveRoleData::clear_ptname() {
  if (ptname_ != &::google::protobuf::internal::kEmptyString) {
    ptname_->clear();
  }
  clear_has_ptname();
}
inline const ::std::string& SResponseSaveRoleData::ptname() const {
  return *ptname_;
}
inline void SResponseSaveRoleData::set_ptname(const ::std::string& value) {
  set_has_ptname();
  if (ptname_ == &::google::protobuf::internal::kEmptyString) {
    ptname_ = new ::std::string;
  }
  ptname_->assign(value);
}
inline void SResponseSaveRoleData::set_ptname(const char* value) {
  set_has_ptname();
  if (ptname_ == &::google::protobuf::internal::kEmptyString) {
    ptname_ = new ::std::string;
  }
  ptname_->assign(value);
}
inline void SResponseSaveRoleData::set_ptname(const char* value, size_t size) {
  set_has_ptname();
  if (ptname_ == &::google::protobuf::internal::kEmptyString) {
    ptname_ = new ::std::string;
  }
  ptname_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* SResponseSaveRoleData::mutable_ptname() {
  set_has_ptname();
  if (ptname_ == &::google::protobuf::internal::kEmptyString) {
    ptname_ = new ::std::string;
  }
  return ptname_;
}
inline ::std::string* SResponseSaveRoleData::release_ptname() {
  clear_has_ptname();
  if (ptname_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = ptname_;
    ptname_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}

// optional uint32 errCode = 2;
inline bool SResponseSaveRoleData::has_errcode() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void SResponseSaveRoleData::set_has_errcode() {
  _has_bits_[0] |= 0x00000002u;
}
inline void SResponseSaveRoleData::clear_has_errcode() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void SResponseSaveRoleData::clear_errcode() {
  errcode_ = 0u;
  clear_has_errcode();
}
inline ::google::protobuf::uint32 SResponseSaveRoleData::errcode() const {
  return errcode_;
}
inline void SResponseSaveRoleData::set_errcode(::google::protobuf::uint32 value) {
  set_has_errcode();
  errcode_ = value;
}

// -------------------------------------------------------------------

// SRequestRoleDataVersion

// optional string ptName = 1;
inline bool SRequestRoleDataVersion::has_ptname() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void SRequestRoleDataVersion::set_has_ptname() {
  _has_bits_[0] |= 0x00000001u;
}
inline void SRequestRoleDataVersion::clear_has_ptname() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void SRequestRoleDataVersion::clear_ptname() {
  if (ptname_ != &::google::protobuf::internal::kEmptyString) {
    ptname_->clear();
  }
  clear_has_ptname();
}
inline const ::std::string& SRequestRoleDataVersion::ptname() const {
  return *ptname_;
}
inline void SRequestRoleDataVersion::set_ptname(const ::std::string& value) {
  set_has_ptname();
  if (ptname_ == &::google::protobuf::internal::kEmptyString) {
    ptname_ = new ::std::string;
  }
  ptname_->assign(value);
}
inline void SRequestRoleDataVersion::set_ptname(const char* value) {
  set_has_ptname();
  if (ptname_ == &::google::protobuf::internal::kEmptyString) {
    ptname_ = new ::std::string;
  }
  ptname_->assign(value);
}
inline void SRequestRoleDataVersion::set_ptname(const char* value, size_t size) {
  set_has_ptname();
  if (ptname_ == &::google::protobuf::internal::kEmptyString) {
    ptname_ = new ::std::string;
  }
  ptname_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* SRequestRoleDataVersion::mutable_ptname() {
  set_has_ptname();
  if (ptname_ == &::google::protobuf::internal::kEmptyString) {
    ptname_ = new ::std::string;
  }
  return ptname_;
}
inline ::std::string* SRequestRoleDataVersion::release_ptname() {
  clear_has_ptname();
  if (ptname_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = ptname_;
    ptname_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}

// -------------------------------------------------------------------

// SResponseRoleDataVersion

// optional string ptName = 1;
inline bool SResponseRoleDataVersion::has_ptname() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void SResponseRoleDataVersion::set_has_ptname() {
  _has_bits_[0] |= 0x00000001u;
}
inline void SResponseRoleDataVersion::clear_has_ptname() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void SResponseRoleDataVersion::clear_ptname() {
  if (ptname_ != &::google::protobuf::internal::kEmptyString) {
    ptname_->clear();
  }
  clear_has_ptname();
}
inline const ::std::string& SResponseRoleDataVersion::ptname() const {
  return *ptname_;
}
inline void SResponseRoleDataVersion::set_ptname(const ::std::string& value) {
  set_has_ptname();
  if (ptname_ == &::google::protobuf::internal::kEmptyString) {
    ptname_ = new ::std::string;
  }
  ptname_->assign(value);
}
inline void SResponseRoleDataVersion::set_ptname(const char* value) {
  set_has_ptname();
  if (ptname_ == &::google::protobuf::internal::kEmptyString) {
    ptname_ = new ::std::string;
  }
  ptname_->assign(value);
}
inline void SResponseRoleDataVersion::set_ptname(const char* value, size_t size) {
  set_has_ptname();
  if (ptname_ == &::google::protobuf::internal::kEmptyString) {
    ptname_ = new ::std::string;
  }
  ptname_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* SResponseRoleDataVersion::mutable_ptname() {
  set_has_ptname();
  if (ptname_ == &::google::protobuf::internal::kEmptyString) {
    ptname_ = new ::std::string;
  }
  return ptname_;
}
inline ::std::string* SResponseRoleDataVersion::release_ptname() {
  clear_has_ptname();
  if (ptname_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = ptname_;
    ptname_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}

// optional uint32 dataVersion = 2;
inline bool SResponseRoleDataVersion::has_dataversion() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void SResponseRoleDataVersion::set_has_dataversion() {
  _has_bits_[0] |= 0x00000002u;
}
inline void SResponseRoleDataVersion::clear_has_dataversion() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void SResponseRoleDataVersion::clear_dataversion() {
  dataversion_ = 0u;
  clear_has_dataversion();
}
inline ::google::protobuf::uint32 SResponseRoleDataVersion::dataversion() const {
  return dataversion_;
}
inline void SResponseRoleDataVersion::set_dataversion(::google::protobuf::uint32 value) {
  set_has_dataversion();
  dataversion_ = value;
}

// optional uint32 errCode = 3;
inline bool SResponseRoleDataVersion::has_errcode() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void SResponseRoleDataVersion::set_has_errcode() {
  _has_bits_[0] |= 0x00000004u;
}
inline void SResponseRoleDataVersion::clear_has_errcode() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void SResponseRoleDataVersion::clear_errcode() {
  errcode_ = 0u;
  clear_has_errcode();
}
inline ::google::protobuf::uint32 SResponseRoleDataVersion::errcode() const {
  return errcode_;
}
inline void SResponseRoleDataVersion::set_errcode(::google::protobuf::uint32 value) {
  set_has_errcode();
  errcode_ = value;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace gtod

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_DataServer_2eproto__INCLUDED
