// Generated by the protocol buffer compiler.  DO NOT EDIT!

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "LoginProtocol.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace login {

namespace {

const ::google::protobuf::Descriptor* SRequestVerifyToken_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  SRequestVerifyToken_reflection_ = NULL;
const ::google::protobuf::Descriptor* SResponseVerifyToken_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  SResponseVerifyToken_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_LoginProtocol_2eproto() {
  protobuf_AddDesc_LoginProtocol_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "LoginProtocol.proto");
  GOOGLE_CHECK(file != NULL);
  SRequestVerifyToken_descriptor_ = file->message_type(0);
  static const int SRequestVerifyToken_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SRequestVerifyToken, ptname_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SRequestVerifyToken, token_),
  };
  SRequestVerifyToken_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      SRequestVerifyToken_descriptor_,
      SRequestVerifyToken::default_instance_,
      SRequestVerifyToken_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SRequestVerifyToken, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SRequestVerifyToken, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(SRequestVerifyToken));
  SResponseVerifyToken_descriptor_ = file->message_type(1);
  static const int SResponseVerifyToken_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SResponseVerifyToken, ptname_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SResponseVerifyToken, errcode_),
  };
  SResponseVerifyToken_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      SResponseVerifyToken_descriptor_,
      SResponseVerifyToken::default_instance_,
      SResponseVerifyToken_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SResponseVerifyToken, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SResponseVerifyToken, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(SResponseVerifyToken));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_LoginProtocol_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    SRequestVerifyToken_descriptor_, &SRequestVerifyToken::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    SResponseVerifyToken_descriptor_, &SResponseVerifyToken::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_LoginProtocol_2eproto() {
  delete SRequestVerifyToken::default_instance_;
  delete SRequestVerifyToken_reflection_;
  delete SResponseVerifyToken::default_instance_;
  delete SResponseVerifyToken_reflection_;
}

void protobuf_AddDesc_LoginProtocol_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\023LoginProtocol.proto\022\005login\"4\n\023SRequest"
    "VerifyToken\022\016\n\006ptName\030\001 \001(\t\022\r\n\005token\030\002 \001"
    "(\t\"7\n\024SResponseVerifyToken\022\016\n\006ptName\030\001 \001"
    "(\t\022\017\n\007errCode\030\002 \001(\r", 139);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "LoginProtocol.proto", &protobuf_RegisterTypes);
  SRequestVerifyToken::default_instance_ = new SRequestVerifyToken();
  SResponseVerifyToken::default_instance_ = new SResponseVerifyToken();
  SRequestVerifyToken::default_instance_->InitAsDefaultInstance();
  SResponseVerifyToken::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_LoginProtocol_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_LoginProtocol_2eproto {
  StaticDescriptorInitializer_LoginProtocol_2eproto() {
    protobuf_AddDesc_LoginProtocol_2eproto();
  }
} static_descriptor_initializer_LoginProtocol_2eproto_;


// ===================================================================

#ifndef _MSC_VER
const int SRequestVerifyToken::kPtNameFieldNumber;
const int SRequestVerifyToken::kTokenFieldNumber;
#endif  // !_MSC_VER

SRequestVerifyToken::SRequestVerifyToken()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void SRequestVerifyToken::InitAsDefaultInstance() {
}

SRequestVerifyToken::SRequestVerifyToken(const SRequestVerifyToken& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void SRequestVerifyToken::SharedCtor() {
  _cached_size_ = 0;
  ptname_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  token_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

SRequestVerifyToken::~SRequestVerifyToken() {
  SharedDtor();
}

void SRequestVerifyToken::SharedDtor() {
  if (ptname_ != &::google::protobuf::internal::kEmptyString) {
    delete ptname_;
  }
  if (token_ != &::google::protobuf::internal::kEmptyString) {
    delete token_;
  }
  if (this != default_instance_) {
  }
}

void SRequestVerifyToken::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* SRequestVerifyToken::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return SRequestVerifyToken_descriptor_;
}

const SRequestVerifyToken& SRequestVerifyToken::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_LoginProtocol_2eproto();  return *default_instance_;
}

SRequestVerifyToken* SRequestVerifyToken::default_instance_ = NULL;

SRequestVerifyToken* SRequestVerifyToken::New() const {
  return new SRequestVerifyToken;
}

void SRequestVerifyToken::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (has_ptname()) {
      if (ptname_ != &::google::protobuf::internal::kEmptyString) {
        ptname_->clear();
      }
    }
    if (has_token()) {
      if (token_ != &::google::protobuf::internal::kEmptyString) {
        token_->clear();
      }
    }
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool SRequestVerifyToken::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional string ptName = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_ptname()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->ptname().data(), this->ptname().length(),
            ::google::protobuf::internal::WireFormat::PARSE);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(18)) goto parse_token;
        break;
      }
      
      // optional string token = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_token:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_token()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->token().data(), this->token().length(),
            ::google::protobuf::internal::WireFormat::PARSE);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }
      
      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void SRequestVerifyToken::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // optional string ptName = 1;
  if (has_ptname()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->ptname().data(), this->ptname().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      1, this->ptname(), output);
  }
  
  // optional string token = 2;
  if (has_token()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->token().data(), this->token().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      2, this->token(), output);
  }
  
  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* SRequestVerifyToken::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // optional string ptName = 1;
  if (has_ptname()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->ptname().data(), this->ptname().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->ptname(), target);
  }
  
  // optional string token = 2;
  if (has_token()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->token().data(), this->token().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->token(), target);
  }
  
  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int SRequestVerifyToken::ByteSize() const {
  int total_size = 0;
  
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // optional string ptName = 1;
    if (has_ptname()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->ptname());
    }
    
    // optional string token = 2;
    if (has_token()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->token());
    }
    
  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void SRequestVerifyToken::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const SRequestVerifyToken* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const SRequestVerifyToken*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void SRequestVerifyToken::MergeFrom(const SRequestVerifyToken& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_ptname()) {
      set_ptname(from.ptname());
    }
    if (from.has_token()) {
      set_token(from.token());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void SRequestVerifyToken::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void SRequestVerifyToken::CopyFrom(const SRequestVerifyToken& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SRequestVerifyToken::IsInitialized() const {
  
  return true;
}

void SRequestVerifyToken::Swap(SRequestVerifyToken* other) {
  if (other != this) {
    std::swap(ptname_, other->ptname_);
    std::swap(token_, other->token_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata SRequestVerifyToken::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = SRequestVerifyToken_descriptor_;
  metadata.reflection = SRequestVerifyToken_reflection_;
  return metadata;
}


// ===================================================================

#ifndef _MSC_VER
const int SResponseVerifyToken::kPtNameFieldNumber;
const int SResponseVerifyToken::kErrCodeFieldNumber;
#endif  // !_MSC_VER

SResponseVerifyToken::SResponseVerifyToken()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void SResponseVerifyToken::InitAsDefaultInstance() {
}

SResponseVerifyToken::SResponseVerifyToken(const SResponseVerifyToken& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void SResponseVerifyToken::SharedCtor() {
  _cached_size_ = 0;
  ptname_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  errcode_ = 0u;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

SResponseVerifyToken::~SResponseVerifyToken() {
  SharedDtor();
}

void SResponseVerifyToken::SharedDtor() {
  if (ptname_ != &::google::protobuf::internal::kEmptyString) {
    delete ptname_;
  }
  if (this != default_instance_) {
  }
}

void SResponseVerifyToken::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* SResponseVerifyToken::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return SResponseVerifyToken_descriptor_;
}

const SResponseVerifyToken& SResponseVerifyToken::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_LoginProtocol_2eproto();  return *default_instance_;
}

SResponseVerifyToken* SResponseVerifyToken::default_instance_ = NULL;

SResponseVerifyToken* SResponseVerifyToken::New() const {
  return new SResponseVerifyToken;
}

void SResponseVerifyToken::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (has_ptname()) {
      if (ptname_ != &::google::protobuf::internal::kEmptyString) {
        ptname_->clear();
      }
    }
    errcode_ = 0u;
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool SResponseVerifyToken::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional string ptName = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_ptname()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->ptname().data(), this->ptname().length(),
            ::google::protobuf::internal::WireFormat::PARSE);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(16)) goto parse_errCode;
        break;
      }
      
      // optional uint32 errCode = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_errCode:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &errcode_)));
          set_has_errcode();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }
      
      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void SResponseVerifyToken::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // optional string ptName = 1;
  if (has_ptname()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->ptname().data(), this->ptname().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      1, this->ptname(), output);
  }
  
  // optional uint32 errCode = 2;
  if (has_errcode()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(2, this->errcode(), output);
  }
  
  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* SResponseVerifyToken::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // optional string ptName = 1;
  if (has_ptname()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->ptname().data(), this->ptname().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->ptname(), target);
  }
  
  // optional uint32 errCode = 2;
  if (has_errcode()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(2, this->errcode(), target);
  }
  
  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int SResponseVerifyToken::ByteSize() const {
  int total_size = 0;
  
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // optional string ptName = 1;
    if (has_ptname()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->ptname());
    }
    
    // optional uint32 errCode = 2;
    if (has_errcode()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->errcode());
    }
    
  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void SResponseVerifyToken::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const SResponseVerifyToken* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const SResponseVerifyToken*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void SResponseVerifyToken::MergeFrom(const SResponseVerifyToken& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_ptname()) {
      set_ptname(from.ptname());
    }
    if (from.has_errcode()) {
      set_errcode(from.errcode());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void SResponseVerifyToken::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void SResponseVerifyToken::CopyFrom(const SResponseVerifyToken& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SResponseVerifyToken::IsInitialized() const {
  
  return true;
}

void SResponseVerifyToken::Swap(SResponseVerifyToken* other) {
  if (other != this) {
    std::swap(ptname_, other->ptname_);
    std::swap(errcode_, other->errcode_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata SResponseVerifyToken::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = SResponseVerifyToken_descriptor_;
  metadata.reflection = SResponseVerifyToken_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace login

// @@protoc_insertion_point(global_scope)
