# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


import RoleData_pb2

DESCRIPTOR = descriptor.FileDescriptor(
  name='DataServer.proto',
  package='gtod',
  serialized_pb='\n\x10\x44\x61taServer.proto\x12\x04gtod\x1a\x0eRoleData.proto\"6\n\x12SRequestCreateRole\x12\x0e\n\x06ptName\x18\x01 \x01(\t\x12\x10\n\x08roleName\x18\x02 \x01(\t\"6\n\x13SResponseCreateRole\x12\x0e\n\x06ptName\x18\x01 \x01(\t\x12\x0f\n\x07\x65rrCode\x18\x02 \x01(\r\"\"\n\x10SRequestRoleData\x12\x0e\n\x06ptName\x18\x01 \x01(\t\"Q\n\x11SResponseRoleData\x12\x0f\n\x07\x65rrCode\x18\x01 \x01(\r\x12+\n\x08roleData\x18\x02 \x01(\x0b\x32\x19.roledata.PBRoleTotalInfo\"S\n\x14SRequestSaveRoleData\x12\x0e\n\x06ptName\x18\x01 \x01(\t\x12+\n\x08roleData\x18\x02 \x01(\x0b\x32\x19.roledata.PBRoleTotalInfo\"8\n\x15SResponseSaveRoleData\x12\x0e\n\x06ptName\x18\x01 \x01(\t\x12\x0f\n\x07\x65rrCode\x18\x02 \x01(\r\")\n\x17SRequestRoleDataVersion\x12\x0e\n\x06ptName\x18\x01 \x01(\t\"P\n\x18SResponseRoleDataVersion\x12\x0e\n\x06ptName\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x61taVersion\x18\x02 \x01(\r\x12\x0f\n\x07\x65rrCode\x18\x03 \x01(\r')




_SREQUESTCREATEROLE = descriptor.Descriptor(
  name='SRequestCreateRole',
  full_name='gtod.SRequestCreateRole',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='ptName', full_name='gtod.SRequestCreateRole.ptName', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='roleName', full_name='gtod.SRequestCreateRole.roleName', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=42,
  serialized_end=96,
)


_SRESPONSECREATEROLE = descriptor.Descriptor(
  name='SResponseCreateRole',
  full_name='gtod.SResponseCreateRole',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='ptName', full_name='gtod.SResponseCreateRole.ptName', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='errCode', full_name='gtod.SResponseCreateRole.errCode', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=98,
  serialized_end=152,
)


_SREQUESTROLEDATA = descriptor.Descriptor(
  name='SRequestRoleData',
  full_name='gtod.SRequestRoleData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='ptName', full_name='gtod.SRequestRoleData.ptName', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=154,
  serialized_end=188,
)


_SRESPONSEROLEDATA = descriptor.Descriptor(
  name='SResponseRoleData',
  full_name='gtod.SResponseRoleData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='errCode', full_name='gtod.SResponseRoleData.errCode', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='roleData', full_name='gtod.SResponseRoleData.roleData', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=190,
  serialized_end=271,
)


_SREQUESTSAVEROLEDATA = descriptor.Descriptor(
  name='SRequestSaveRoleData',
  full_name='gtod.SRequestSaveRoleData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='ptName', full_name='gtod.SRequestSaveRoleData.ptName', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='roleData', full_name='gtod.SRequestSaveRoleData.roleData', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=273,
  serialized_end=356,
)


_SRESPONSESAVEROLEDATA = descriptor.Descriptor(
  name='SResponseSaveRoleData',
  full_name='gtod.SResponseSaveRoleData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='ptName', full_name='gtod.SResponseSaveRoleData.ptName', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='errCode', full_name='gtod.SResponseSaveRoleData.errCode', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=358,
  serialized_end=414,
)


_SREQUESTROLEDATAVERSION = descriptor.Descriptor(
  name='SRequestRoleDataVersion',
  full_name='gtod.SRequestRoleDataVersion',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='ptName', full_name='gtod.SRequestRoleDataVersion.ptName', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=416,
  serialized_end=457,
)


_SRESPONSEROLEDATAVERSION = descriptor.Descriptor(
  name='SResponseRoleDataVersion',
  full_name='gtod.SResponseRoleDataVersion',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='ptName', full_name='gtod.SResponseRoleDataVersion.ptName', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='dataVersion', full_name='gtod.SResponseRoleDataVersion.dataVersion', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='errCode', full_name='gtod.SResponseRoleDataVersion.errCode', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=459,
  serialized_end=539,
)

_SRESPONSEROLEDATA.fields_by_name['roleData'].message_type = RoleData_pb2._PBROLETOTALINFO
_SREQUESTSAVEROLEDATA.fields_by_name['roleData'].message_type = RoleData_pb2._PBROLETOTALINFO
DESCRIPTOR.message_types_by_name['SRequestCreateRole'] = _SREQUESTCREATEROLE
DESCRIPTOR.message_types_by_name['SResponseCreateRole'] = _SRESPONSECREATEROLE
DESCRIPTOR.message_types_by_name['SRequestRoleData'] = _SREQUESTROLEDATA
DESCRIPTOR.message_types_by_name['SResponseRoleData'] = _SRESPONSEROLEDATA
DESCRIPTOR.message_types_by_name['SRequestSaveRoleData'] = _SREQUESTSAVEROLEDATA
DESCRIPTOR.message_types_by_name['SResponseSaveRoleData'] = _SRESPONSESAVEROLEDATA
DESCRIPTOR.message_types_by_name['SRequestRoleDataVersion'] = _SREQUESTROLEDATAVERSION
DESCRIPTOR.message_types_by_name['SResponseRoleDataVersion'] = _SRESPONSEROLEDATAVERSION

class SRequestCreateRole(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _SREQUESTCREATEROLE
  
  # @@protoc_insertion_point(class_scope:gtod.SRequestCreateRole)

class SResponseCreateRole(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _SRESPONSECREATEROLE
  
  # @@protoc_insertion_point(class_scope:gtod.SResponseCreateRole)

class SRequestRoleData(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _SREQUESTROLEDATA
  
  # @@protoc_insertion_point(class_scope:gtod.SRequestRoleData)

class SResponseRoleData(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _SRESPONSEROLEDATA
  
  # @@protoc_insertion_point(class_scope:gtod.SResponseRoleData)

class SRequestSaveRoleData(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _SREQUESTSAVEROLEDATA
  
  # @@protoc_insertion_point(class_scope:gtod.SRequestSaveRoleData)

class SResponseSaveRoleData(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _SRESPONSESAVEROLEDATA
  
  # @@protoc_insertion_point(class_scope:gtod.SResponseSaveRoleData)

class SRequestRoleDataVersion(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _SREQUESTROLEDATAVERSION
  
  # @@protoc_insertion_point(class_scope:gtod.SRequestRoleDataVersion)

class SResponseRoleDataVersion(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _SRESPONSEROLEDATAVERSION
  
  # @@protoc_insertion_point(class_scope:gtod.SResponseRoleDataVersion)

# @@protoc_insertion_point(module_scope)
