# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='LobbyProtocol.proto',
  package='lobby',
  serialized_pb='\n\x13LobbyProtocol.proto\x12\x05lobby\"B\n\x14RequestRegGameServer\x12\x0c\n\x04gsId\x18\x01 \x01(\r\x12\x0e\n\x06gsType\x18\x02 \x01(\r\x12\x0c\n\x04port\x18\x03 \x01(\r\"(\n\x15ResponseRegGameServer\x12\x0f\n\x07\x65rrCode\x18\x01 \x01(\r')




_REQUESTREGGAMESERVER = descriptor.Descriptor(
  name='RequestRegGameServer',
  full_name='lobby.RequestRegGameServer',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='gsId', full_name='lobby.RequestRegGameServer.gsId', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='gsType', full_name='lobby.RequestRegGameServer.gsType', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='port', full_name='lobby.RequestRegGameServer.port', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=30,
  serialized_end=96,
)


_RESPONSEREGGAMESERVER = descriptor.Descriptor(
  name='ResponseRegGameServer',
  full_name='lobby.ResponseRegGameServer',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='errCode', full_name='lobby.ResponseRegGameServer.errCode', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=98,
  serialized_end=138,
)

DESCRIPTOR.message_types_by_name['RequestRegGameServer'] = _REQUESTREGGAMESERVER
DESCRIPTOR.message_types_by_name['ResponseRegGameServer'] = _RESPONSEREGGAMESERVER

class RequestRegGameServer(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _REQUESTREGGAMESERVER
  
  # @@protoc_insertion_point(class_scope:lobby.RequestRegGameServer)

class ResponseRegGameServer(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _RESPONSEREGGAMESERVER
  
  # @@protoc_insertion_point(class_scope:lobby.ResponseRegGameServer)

# @@protoc_insertion_point(module_scope)
