# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='LoginProtocol.proto',
  package='login',
  serialized_pb='\n\x13LoginProtocol.proto\x12\x05login\"4\n\x13SRequestVerifyToken\x12\x0e\n\x06ptName\x18\x01 \x01(\t\x12\r\n\x05token\x18\x02 \x01(\t\"7\n\x14SResponseVerifyToken\x12\x0e\n\x06ptName\x18\x01 \x01(\t\x12\x0f\n\x07\x65rrCode\x18\x02 \x01(\r')




_SREQUESTVERIFYTOKEN = descriptor.Descriptor(
  name='SRequestVerifyToken',
  full_name='login.SRequestVerifyToken',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='ptName', full_name='login.SRequestVerifyToken.ptName', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='token', full_name='login.SRequestVerifyToken.token', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=30,
  serialized_end=82,
)


_SRESPONSEVERIFYTOKEN = descriptor.Descriptor(
  name='SResponseVerifyToken',
  full_name='login.SResponseVerifyToken',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='ptName', full_name='login.SResponseVerifyToken.ptName', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='errCode', full_name='login.SResponseVerifyToken.errCode', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=84,
  serialized_end=139,
)

DESCRIPTOR.message_types_by_name['SRequestVerifyToken'] = _SREQUESTVERIFYTOKEN
DESCRIPTOR.message_types_by_name['SResponseVerifyToken'] = _SRESPONSEVERIFYTOKEN

class SRequestVerifyToken(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _SREQUESTVERIFYTOKEN
  
  # @@protoc_insertion_point(class_scope:login.SRequestVerifyToken)

class SResponseVerifyToken(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _SRESPONSEVERIFYTOKEN
  
  # @@protoc_insertion_point(class_scope:login.SResponseVerifyToken)

# @@protoc_insertion_point(module_scope)
