# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='RoleData.proto',
  package='roledata',
  serialized_pb='\n\x0eRoleData.proto\x12\x08roledata\"c\n\x0fPBRoleTotalInfo\x12*\n\x08\x62\x61seInfo\x18\x01 \x01(\x0b\x32\x18.roledata.PBRoleBaseInfo\x12$\n\x07\x62\x61gInfo\x18\x02 \x01(\x0b\x32\x13.roledata.PBRoleBag\"\x80\x02\n\x0ePBRoleBaseInfo\x12\x0e\n\x06userId\x18\x01 \x01(\r\x12\x13\n\x0b\x64\x61taVersion\x18\x02 \x01(\r\x12\x10\n\x08roleName\x18\x03 \x01(\t\x12\x0e\n\x06ptName\x18\x04 \x01(\t\x12\r\n\x05level\x18\x05 \x01(\r\x12\x0b\n\x03\x65xp\x18\x06 \x01(\r\x12\x0f\n\x07\x64iamond\x18\x07 \x01(\r\x12\x0c\n\x04gold\x18\x08 \x01(\r\x12\x10\n\x08vipLevel\x18\t \x01(\r\x12&\n\x08heroList\x18\n \x01(\x0b\x32\x14.roledata.PBHeroList\x12\x32\n\x0e\x62\x61ttleGateList\x18\x0b \x01(\x0b\x32\x1a.roledata.PBBattleGateList\",\n\x07PBEquip\x12\x0f\n\x07\x65quipId\x18\x01 \x01(\r\x12\x10\n\x08\x65quipNum\x18\x03 \x01(\r\"\xa6\x01\n\x06PBHero\x12\x0e\n\x06heroId\x18\x01 \x01(\r\x12\x10\n\x08heroUUID\x18\x02 \x01(\x04\x12\r\n\x05level\x18\x03 \x01(\r\x12\x0b\n\x03\x65xp\x18\x04 \x01(\r\x12\x10\n\x08heroRank\x18\x05 \x01(\r\x12\x14\n\x0cupgradeLevel\x18\x06 \x01(\r\x12\x13\n\x0b\x66ragmentNum\x18\x07 \x01(\r\x12!\n\x06\x65quips\x18\x08 \x03(\x0b\x32\x11.roledata.PBEquip\"-\n\nPBHeroList\x12\x1f\n\x05heros\x18\x01 \x03(\x0b\x32\x10.roledata.PBHero\".\n\tPBRoleBag\x12!\n\x06\x65quips\x18\x01 \x03(\x0b\x32\x11.roledata.PBEquip\"@\n\nPBGateInfo\x12\x0e\n\x06gateId\x18\x01 \x01(\r\x12\x10\n\x08gateStar\x18\x02 \x01(\r\x12\x10\n\x08hasFight\x18\x03 \x01(\x08\"E\n\x0cPBBattleInfo\x12\x10\n\x08\x62\x61ttleId\x18\x01 \x01(\r\x12#\n\x05gates\x18\x02 \x03(\x0b\x32\x14.roledata.PBGateInfo\"?\n\x10PBBattleGateList\x12+\n\x0b\x62\x61ttleGates\x18\x01 \x03(\x0b\x32\x16.roledata.PBBattleInfo')




_PBROLETOTALINFO = descriptor.Descriptor(
  name='PBRoleTotalInfo',
  full_name='roledata.PBRoleTotalInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='baseInfo', full_name='roledata.PBRoleTotalInfo.baseInfo', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='bagInfo', full_name='roledata.PBRoleTotalInfo.bagInfo', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=28,
  serialized_end=127,
)


_PBROLEBASEINFO = descriptor.Descriptor(
  name='PBRoleBaseInfo',
  full_name='roledata.PBRoleBaseInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='userId', full_name='roledata.PBRoleBaseInfo.userId', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='dataVersion', full_name='roledata.PBRoleBaseInfo.dataVersion', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='roleName', full_name='roledata.PBRoleBaseInfo.roleName', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='ptName', full_name='roledata.PBRoleBaseInfo.ptName', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='level', full_name='roledata.PBRoleBaseInfo.level', index=4,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='exp', full_name='roledata.PBRoleBaseInfo.exp', index=5,
      number=6, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='diamond', full_name='roledata.PBRoleBaseInfo.diamond', index=6,
      number=7, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='gold', full_name='roledata.PBRoleBaseInfo.gold', index=7,
      number=8, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='vipLevel', full_name='roledata.PBRoleBaseInfo.vipLevel', index=8,
      number=9, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='heroList', full_name='roledata.PBRoleBaseInfo.heroList', index=9,
      number=10, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='battleGateList', full_name='roledata.PBRoleBaseInfo.battleGateList', index=10,
      number=11, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=130,
  serialized_end=386,
)


_PBEQUIP = descriptor.Descriptor(
  name='PBEquip',
  full_name='roledata.PBEquip',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='equipId', full_name='roledata.PBEquip.equipId', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='equipNum', full_name='roledata.PBEquip.equipNum', index=1,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=388,
  serialized_end=432,
)


_PBHERO = descriptor.Descriptor(
  name='PBHero',
  full_name='roledata.PBHero',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='heroId', full_name='roledata.PBHero.heroId', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='heroUUID', full_name='roledata.PBHero.heroUUID', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='level', full_name='roledata.PBHero.level', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='exp', full_name='roledata.PBHero.exp', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='heroRank', full_name='roledata.PBHero.heroRank', index=4,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='upgradeLevel', full_name='roledata.PBHero.upgradeLevel', index=5,
      number=6, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='fragmentNum', full_name='roledata.PBHero.fragmentNum', index=6,
      number=7, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='equips', full_name='roledata.PBHero.equips', index=7,
      number=8, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=435,
  serialized_end=601,
)


_PBHEROLIST = descriptor.Descriptor(
  name='PBHeroList',
  full_name='roledata.PBHeroList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='heros', full_name='roledata.PBHeroList.heros', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=603,
  serialized_end=648,
)


_PBROLEBAG = descriptor.Descriptor(
  name='PBRoleBag',
  full_name='roledata.PBRoleBag',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='equips', full_name='roledata.PBRoleBag.equips', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=650,
  serialized_end=696,
)


_PBGATEINFO = descriptor.Descriptor(
  name='PBGateInfo',
  full_name='roledata.PBGateInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='gateId', full_name='roledata.PBGateInfo.gateId', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='gateStar', full_name='roledata.PBGateInfo.gateStar', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='hasFight', full_name='roledata.PBGateInfo.hasFight', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=698,
  serialized_end=762,
)


_PBBATTLEINFO = descriptor.Descriptor(
  name='PBBattleInfo',
  full_name='roledata.PBBattleInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='battleId', full_name='roledata.PBBattleInfo.battleId', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='gates', full_name='roledata.PBBattleInfo.gates', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=764,
  serialized_end=833,
)


_PBBATTLEGATELIST = descriptor.Descriptor(
  name='PBBattleGateList',
  full_name='roledata.PBBattleGateList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='battleGates', full_name='roledata.PBBattleGateList.battleGates', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=835,
  serialized_end=898,
)

_PBROLETOTALINFO.fields_by_name['baseInfo'].message_type = _PBROLEBASEINFO
_PBROLETOTALINFO.fields_by_name['bagInfo'].message_type = _PBROLEBAG
_PBROLEBASEINFO.fields_by_name['heroList'].message_type = _PBHEROLIST
_PBROLEBASEINFO.fields_by_name['battleGateList'].message_type = _PBBATTLEGATELIST
_PBHERO.fields_by_name['equips'].message_type = _PBEQUIP
_PBHEROLIST.fields_by_name['heros'].message_type = _PBHERO
_PBROLEBAG.fields_by_name['equips'].message_type = _PBEQUIP
_PBBATTLEINFO.fields_by_name['gates'].message_type = _PBGATEINFO
_PBBATTLEGATELIST.fields_by_name['battleGates'].message_type = _PBBATTLEINFO
DESCRIPTOR.message_types_by_name['PBRoleTotalInfo'] = _PBROLETOTALINFO
DESCRIPTOR.message_types_by_name['PBRoleBaseInfo'] = _PBROLEBASEINFO
DESCRIPTOR.message_types_by_name['PBEquip'] = _PBEQUIP
DESCRIPTOR.message_types_by_name['PBHero'] = _PBHERO
DESCRIPTOR.message_types_by_name['PBHeroList'] = _PBHEROLIST
DESCRIPTOR.message_types_by_name['PBRoleBag'] = _PBROLEBAG
DESCRIPTOR.message_types_by_name['PBGateInfo'] = _PBGATEINFO
DESCRIPTOR.message_types_by_name['PBBattleInfo'] = _PBBATTLEINFO
DESCRIPTOR.message_types_by_name['PBBattleGateList'] = _PBBATTLEGATELIST

class PBRoleTotalInfo(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PBROLETOTALINFO
  
  # @@protoc_insertion_point(class_scope:roledata.PBRoleTotalInfo)

class PBRoleBaseInfo(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PBROLEBASEINFO
  
  # @@protoc_insertion_point(class_scope:roledata.PBRoleBaseInfo)

class PBEquip(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PBEQUIP
  
  # @@protoc_insertion_point(class_scope:roledata.PBEquip)

class PBHero(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PBHERO
  
  # @@protoc_insertion_point(class_scope:roledata.PBHero)

class PBHeroList(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PBHEROLIST
  
  # @@protoc_insertion_point(class_scope:roledata.PBHeroList)

class PBRoleBag(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PBROLEBAG
  
  # @@protoc_insertion_point(class_scope:roledata.PBRoleBag)

class PBGateInfo(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PBGATEINFO
  
  # @@protoc_insertion_point(class_scope:roledata.PBGateInfo)

class PBBattleInfo(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PBBATTLEINFO
  
  # @@protoc_insertion_point(class_scope:roledata.PBBattleInfo)

class PBBattleGateList(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PBBATTLEGATELIST
  
  # @@protoc_insertion_point(class_scope:roledata.PBBattleGateList)

# @@protoc_insertion_point(module_scope)
