// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: LobbyProtocol.proto

package lobby;

public final class LobbyProtocol {
  private LobbyProtocol() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface RequestRegGameServerOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional uint32 gsId = 1;
    boolean hasGsId();
    int getGsId();
    
    // optional uint32 gsType = 2;
    boolean hasGsType();
    int getGsType();
    
    // optional uint32 port = 3;
    boolean hasPort();
    int getPort();
  }
  public static final class RequestRegGameServer extends
      com.google.protobuf.GeneratedMessage
      implements RequestRegGameServerOrBuilder {
    // Use RequestRegGameServer.newBuilder() to construct.
    private RequestRegGameServer(Builder builder) {
      super(builder);
    }
    private RequestRegGameServer(boolean noInit) {}
    
    private static final RequestRegGameServer defaultInstance;
    public static RequestRegGameServer getDefaultInstance() {
      return defaultInstance;
    }
    
    public RequestRegGameServer getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return lobby.LobbyProtocol.internal_static_lobby_RequestRegGameServer_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return lobby.LobbyProtocol.internal_static_lobby_RequestRegGameServer_fieldAccessorTable;
    }
    
    private int bitField0_;
    // optional uint32 gsId = 1;
    public static final int GSID_FIELD_NUMBER = 1;
    private int gsId_;
    public boolean hasGsId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getGsId() {
      return gsId_;
    }
    
    // optional uint32 gsType = 2;
    public static final int GSTYPE_FIELD_NUMBER = 2;
    private int gsType_;
    public boolean hasGsType() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public int getGsType() {
      return gsType_;
    }
    
    // optional uint32 port = 3;
    public static final int PORT_FIELD_NUMBER = 3;
    private int port_;
    public boolean hasPort() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public int getPort() {
      return port_;
    }
    
    private void initFields() {
      gsId_ = 0;
      gsType_ = 0;
      port_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt32(1, gsId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeUInt32(2, gsType_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeUInt32(3, port_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, gsId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, gsType_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(3, port_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static lobby.LobbyProtocol.RequestRegGameServer parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static lobby.LobbyProtocol.RequestRegGameServer parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static lobby.LobbyProtocol.RequestRegGameServer parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static lobby.LobbyProtocol.RequestRegGameServer parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static lobby.LobbyProtocol.RequestRegGameServer parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static lobby.LobbyProtocol.RequestRegGameServer parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static lobby.LobbyProtocol.RequestRegGameServer parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static lobby.LobbyProtocol.RequestRegGameServer parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static lobby.LobbyProtocol.RequestRegGameServer parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static lobby.LobbyProtocol.RequestRegGameServer parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(lobby.LobbyProtocol.RequestRegGameServer prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements lobby.LobbyProtocol.RequestRegGameServerOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return lobby.LobbyProtocol.internal_static_lobby_RequestRegGameServer_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return lobby.LobbyProtocol.internal_static_lobby_RequestRegGameServer_fieldAccessorTable;
      }
      
      // Construct using lobby.LobbyProtocol.RequestRegGameServer.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        gsId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        gsType_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        port_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return lobby.LobbyProtocol.RequestRegGameServer.getDescriptor();
      }
      
      public lobby.LobbyProtocol.RequestRegGameServer getDefaultInstanceForType() {
        return lobby.LobbyProtocol.RequestRegGameServer.getDefaultInstance();
      }
      
      public lobby.LobbyProtocol.RequestRegGameServer build() {
        lobby.LobbyProtocol.RequestRegGameServer result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private lobby.LobbyProtocol.RequestRegGameServer buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        lobby.LobbyProtocol.RequestRegGameServer result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public lobby.LobbyProtocol.RequestRegGameServer buildPartial() {
        lobby.LobbyProtocol.RequestRegGameServer result = new lobby.LobbyProtocol.RequestRegGameServer(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.gsId_ = gsId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.gsType_ = gsType_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.port_ = port_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof lobby.LobbyProtocol.RequestRegGameServer) {
          return mergeFrom((lobby.LobbyProtocol.RequestRegGameServer)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(lobby.LobbyProtocol.RequestRegGameServer other) {
        if (other == lobby.LobbyProtocol.RequestRegGameServer.getDefaultInstance()) return this;
        if (other.hasGsId()) {
          setGsId(other.getGsId());
        }
        if (other.hasGsType()) {
          setGsType(other.getGsType());
        }
        if (other.hasPort()) {
          setPort(other.getPort());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              gsId_ = input.readUInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              gsType_ = input.readUInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              port_ = input.readUInt32();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional uint32 gsId = 1;
      private int gsId_ ;
      public boolean hasGsId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getGsId() {
        return gsId_;
      }
      public Builder setGsId(int value) {
        bitField0_ |= 0x00000001;
        gsId_ = value;
        onChanged();
        return this;
      }
      public Builder clearGsId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        gsId_ = 0;
        onChanged();
        return this;
      }
      
      // optional uint32 gsType = 2;
      private int gsType_ ;
      public boolean hasGsType() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public int getGsType() {
        return gsType_;
      }
      public Builder setGsType(int value) {
        bitField0_ |= 0x00000002;
        gsType_ = value;
        onChanged();
        return this;
      }
      public Builder clearGsType() {
        bitField0_ = (bitField0_ & ~0x00000002);
        gsType_ = 0;
        onChanged();
        return this;
      }
      
      // optional uint32 port = 3;
      private int port_ ;
      public boolean hasPort() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public int getPort() {
        return port_;
      }
      public Builder setPort(int value) {
        bitField0_ |= 0x00000004;
        port_ = value;
        onChanged();
        return this;
      }
      public Builder clearPort() {
        bitField0_ = (bitField0_ & ~0x00000004);
        port_ = 0;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:lobby.RequestRegGameServer)
    }
    
    static {
      defaultInstance = new RequestRegGameServer(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:lobby.RequestRegGameServer)
  }
  
  public interface ResponseRegGameServerOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional uint32 errCode = 1;
    boolean hasErrCode();
    int getErrCode();
  }
  public static final class ResponseRegGameServer extends
      com.google.protobuf.GeneratedMessage
      implements ResponseRegGameServerOrBuilder {
    // Use ResponseRegGameServer.newBuilder() to construct.
    private ResponseRegGameServer(Builder builder) {
      super(builder);
    }
    private ResponseRegGameServer(boolean noInit) {}
    
    private static final ResponseRegGameServer defaultInstance;
    public static ResponseRegGameServer getDefaultInstance() {
      return defaultInstance;
    }
    
    public ResponseRegGameServer getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return lobby.LobbyProtocol.internal_static_lobby_ResponseRegGameServer_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return lobby.LobbyProtocol.internal_static_lobby_ResponseRegGameServer_fieldAccessorTable;
    }
    
    private int bitField0_;
    // optional uint32 errCode = 1;
    public static final int ERRCODE_FIELD_NUMBER = 1;
    private int errCode_;
    public boolean hasErrCode() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getErrCode() {
      return errCode_;
    }
    
    private void initFields() {
      errCode_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt32(1, errCode_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, errCode_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static lobby.LobbyProtocol.ResponseRegGameServer parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static lobby.LobbyProtocol.ResponseRegGameServer parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static lobby.LobbyProtocol.ResponseRegGameServer parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static lobby.LobbyProtocol.ResponseRegGameServer parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static lobby.LobbyProtocol.ResponseRegGameServer parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static lobby.LobbyProtocol.ResponseRegGameServer parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static lobby.LobbyProtocol.ResponseRegGameServer parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static lobby.LobbyProtocol.ResponseRegGameServer parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static lobby.LobbyProtocol.ResponseRegGameServer parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static lobby.LobbyProtocol.ResponseRegGameServer parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(lobby.LobbyProtocol.ResponseRegGameServer prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements lobby.LobbyProtocol.ResponseRegGameServerOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return lobby.LobbyProtocol.internal_static_lobby_ResponseRegGameServer_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return lobby.LobbyProtocol.internal_static_lobby_ResponseRegGameServer_fieldAccessorTable;
      }
      
      // Construct using lobby.LobbyProtocol.ResponseRegGameServer.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        errCode_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return lobby.LobbyProtocol.ResponseRegGameServer.getDescriptor();
      }
      
      public lobby.LobbyProtocol.ResponseRegGameServer getDefaultInstanceForType() {
        return lobby.LobbyProtocol.ResponseRegGameServer.getDefaultInstance();
      }
      
      public lobby.LobbyProtocol.ResponseRegGameServer build() {
        lobby.LobbyProtocol.ResponseRegGameServer result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private lobby.LobbyProtocol.ResponseRegGameServer buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        lobby.LobbyProtocol.ResponseRegGameServer result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public lobby.LobbyProtocol.ResponseRegGameServer buildPartial() {
        lobby.LobbyProtocol.ResponseRegGameServer result = new lobby.LobbyProtocol.ResponseRegGameServer(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.errCode_ = errCode_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof lobby.LobbyProtocol.ResponseRegGameServer) {
          return mergeFrom((lobby.LobbyProtocol.ResponseRegGameServer)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(lobby.LobbyProtocol.ResponseRegGameServer other) {
        if (other == lobby.LobbyProtocol.ResponseRegGameServer.getDefaultInstance()) return this;
        if (other.hasErrCode()) {
          setErrCode(other.getErrCode());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              errCode_ = input.readUInt32();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional uint32 errCode = 1;
      private int errCode_ ;
      public boolean hasErrCode() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getErrCode() {
        return errCode_;
      }
      public Builder setErrCode(int value) {
        bitField0_ |= 0x00000001;
        errCode_ = value;
        onChanged();
        return this;
      }
      public Builder clearErrCode() {
        bitField0_ = (bitField0_ & ~0x00000001);
        errCode_ = 0;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:lobby.ResponseRegGameServer)
    }
    
    static {
      defaultInstance = new ResponseRegGameServer(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:lobby.ResponseRegGameServer)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_lobby_RequestRegGameServer_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_lobby_RequestRegGameServer_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_lobby_ResponseRegGameServer_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_lobby_ResponseRegGameServer_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023LobbyProtocol.proto\022\005lobby\"B\n\024RequestR" +
      "egGameServer\022\014\n\004gsId\030\001 \001(\r\022\016\n\006gsType\030\002 \001" +
      "(\r\022\014\n\004port\030\003 \001(\r\"(\n\025ResponseRegGameServe" +
      "r\022\017\n\007errCode\030\001 \001(\r"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_lobby_RequestRegGameServer_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_lobby_RequestRegGameServer_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_lobby_RequestRegGameServer_descriptor,
              new java.lang.String[] { "GsId", "GsType", "Port", },
              lobby.LobbyProtocol.RequestRegGameServer.class,
              lobby.LobbyProtocol.RequestRegGameServer.Builder.class);
          internal_static_lobby_ResponseRegGameServer_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_lobby_ResponseRegGameServer_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_lobby_ResponseRegGameServer_descriptor,
              new java.lang.String[] { "ErrCode", },
              lobby.LobbyProtocol.ResponseRegGameServer.class,
              lobby.LobbyProtocol.ResponseRegGameServer.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
