// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ServerCmd.proto

package scmd;

public final class ServerCmd {
  private ServerCmd() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface RequestStopServerOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional uint32 serverId = 1;
    boolean hasServerId();
    int getServerId();
  }
  public static final class RequestStopServer extends
      com.google.protobuf.GeneratedMessage
      implements RequestStopServerOrBuilder {
    // Use RequestStopServer.newBuilder() to construct.
    private RequestStopServer(Builder builder) {
      super(builder);
    }
    private RequestStopServer(boolean noInit) {}
    
    private static final RequestStopServer defaultInstance;
    public static RequestStopServer getDefaultInstance() {
      return defaultInstance;
    }
    
    public RequestStopServer getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return scmd.ServerCmd.internal_static_scmd_RequestStopServer_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return scmd.ServerCmd.internal_static_scmd_RequestStopServer_fieldAccessorTable;
    }
    
    private int bitField0_;
    // optional uint32 serverId = 1;
    public static final int SERVERID_FIELD_NUMBER = 1;
    private int serverId_;
    public boolean hasServerId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getServerId() {
      return serverId_;
    }
    
    private void initFields() {
      serverId_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt32(1, serverId_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, serverId_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static scmd.ServerCmd.RequestStopServer parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static scmd.ServerCmd.RequestStopServer parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static scmd.ServerCmd.RequestStopServer parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static scmd.ServerCmd.RequestStopServer parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static scmd.ServerCmd.RequestStopServer parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static scmd.ServerCmd.RequestStopServer parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static scmd.ServerCmd.RequestStopServer parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static scmd.ServerCmd.RequestStopServer parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static scmd.ServerCmd.RequestStopServer parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static scmd.ServerCmd.RequestStopServer parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(scmd.ServerCmd.RequestStopServer prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements scmd.ServerCmd.RequestStopServerOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return scmd.ServerCmd.internal_static_scmd_RequestStopServer_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return scmd.ServerCmd.internal_static_scmd_RequestStopServer_fieldAccessorTable;
      }
      
      // Construct using scmd.ServerCmd.RequestStopServer.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        serverId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return scmd.ServerCmd.RequestStopServer.getDescriptor();
      }
      
      public scmd.ServerCmd.RequestStopServer getDefaultInstanceForType() {
        return scmd.ServerCmd.RequestStopServer.getDefaultInstance();
      }
      
      public scmd.ServerCmd.RequestStopServer build() {
        scmd.ServerCmd.RequestStopServer result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private scmd.ServerCmd.RequestStopServer buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        scmd.ServerCmd.RequestStopServer result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public scmd.ServerCmd.RequestStopServer buildPartial() {
        scmd.ServerCmd.RequestStopServer result = new scmd.ServerCmd.RequestStopServer(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.serverId_ = serverId_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof scmd.ServerCmd.RequestStopServer) {
          return mergeFrom((scmd.ServerCmd.RequestStopServer)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(scmd.ServerCmd.RequestStopServer other) {
        if (other == scmd.ServerCmd.RequestStopServer.getDefaultInstance()) return this;
        if (other.hasServerId()) {
          setServerId(other.getServerId());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              serverId_ = input.readUInt32();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional uint32 serverId = 1;
      private int serverId_ ;
      public boolean hasServerId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getServerId() {
        return serverId_;
      }
      public Builder setServerId(int value) {
        bitField0_ |= 0x00000001;
        serverId_ = value;
        onChanged();
        return this;
      }
      public Builder clearServerId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        serverId_ = 0;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:scmd.RequestStopServer)
    }
    
    static {
      defaultInstance = new RequestStopServer(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:scmd.RequestStopServer)
  }
  
  public interface RequestReloadConfOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional uint32 serverId = 1;
    boolean hasServerId();
    int getServerId();
    
    // optional string confFile = 2;
    boolean hasConfFile();
    String getConfFile();
  }
  public static final class RequestReloadConf extends
      com.google.protobuf.GeneratedMessage
      implements RequestReloadConfOrBuilder {
    // Use RequestReloadConf.newBuilder() to construct.
    private RequestReloadConf(Builder builder) {
      super(builder);
    }
    private RequestReloadConf(boolean noInit) {}
    
    private static final RequestReloadConf defaultInstance;
    public static RequestReloadConf getDefaultInstance() {
      return defaultInstance;
    }
    
    public RequestReloadConf getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return scmd.ServerCmd.internal_static_scmd_RequestReloadConf_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return scmd.ServerCmd.internal_static_scmd_RequestReloadConf_fieldAccessorTable;
    }
    
    private int bitField0_;
    // optional uint32 serverId = 1;
    public static final int SERVERID_FIELD_NUMBER = 1;
    private int serverId_;
    public boolean hasServerId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getServerId() {
      return serverId_;
    }
    
    // optional string confFile = 2;
    public static final int CONFFILE_FIELD_NUMBER = 2;
    private java.lang.Object confFile_;
    public boolean hasConfFile() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getConfFile() {
      java.lang.Object ref = confFile_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          confFile_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getConfFileBytes() {
      java.lang.Object ref = confFile_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        confFile_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    private void initFields() {
      serverId_ = 0;
      confFile_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt32(1, serverId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getConfFileBytes());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, serverId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getConfFileBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static scmd.ServerCmd.RequestReloadConf parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static scmd.ServerCmd.RequestReloadConf parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static scmd.ServerCmd.RequestReloadConf parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static scmd.ServerCmd.RequestReloadConf parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static scmd.ServerCmd.RequestReloadConf parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static scmd.ServerCmd.RequestReloadConf parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static scmd.ServerCmd.RequestReloadConf parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static scmd.ServerCmd.RequestReloadConf parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static scmd.ServerCmd.RequestReloadConf parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static scmd.ServerCmd.RequestReloadConf parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(scmd.ServerCmd.RequestReloadConf prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements scmd.ServerCmd.RequestReloadConfOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return scmd.ServerCmd.internal_static_scmd_RequestReloadConf_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return scmd.ServerCmd.internal_static_scmd_RequestReloadConf_fieldAccessorTable;
      }
      
      // Construct using scmd.ServerCmd.RequestReloadConf.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        serverId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        confFile_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return scmd.ServerCmd.RequestReloadConf.getDescriptor();
      }
      
      public scmd.ServerCmd.RequestReloadConf getDefaultInstanceForType() {
        return scmd.ServerCmd.RequestReloadConf.getDefaultInstance();
      }
      
      public scmd.ServerCmd.RequestReloadConf build() {
        scmd.ServerCmd.RequestReloadConf result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private scmd.ServerCmd.RequestReloadConf buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        scmd.ServerCmd.RequestReloadConf result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public scmd.ServerCmd.RequestReloadConf buildPartial() {
        scmd.ServerCmd.RequestReloadConf result = new scmd.ServerCmd.RequestReloadConf(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.serverId_ = serverId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.confFile_ = confFile_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof scmd.ServerCmd.RequestReloadConf) {
          return mergeFrom((scmd.ServerCmd.RequestReloadConf)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(scmd.ServerCmd.RequestReloadConf other) {
        if (other == scmd.ServerCmd.RequestReloadConf.getDefaultInstance()) return this;
        if (other.hasServerId()) {
          setServerId(other.getServerId());
        }
        if (other.hasConfFile()) {
          setConfFile(other.getConfFile());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              serverId_ = input.readUInt32();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              confFile_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional uint32 serverId = 1;
      private int serverId_ ;
      public boolean hasServerId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getServerId() {
        return serverId_;
      }
      public Builder setServerId(int value) {
        bitField0_ |= 0x00000001;
        serverId_ = value;
        onChanged();
        return this;
      }
      public Builder clearServerId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        serverId_ = 0;
        onChanged();
        return this;
      }
      
      // optional string confFile = 2;
      private java.lang.Object confFile_ = "";
      public boolean hasConfFile() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getConfFile() {
        java.lang.Object ref = confFile_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          confFile_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setConfFile(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        confFile_ = value;
        onChanged();
        return this;
      }
      public Builder clearConfFile() {
        bitField0_ = (bitField0_ & ~0x00000002);
        confFile_ = getDefaultInstance().getConfFile();
        onChanged();
        return this;
      }
      void setConfFile(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        confFile_ = value;
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:scmd.RequestReloadConf)
    }
    
    static {
      defaultInstance = new RequestReloadConf(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:scmd.RequestReloadConf)
  }
  
  public interface ResponseReloadConfOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional uint32 errCode = 1;
    boolean hasErrCode();
    int getErrCode();
  }
  public static final class ResponseReloadConf extends
      com.google.protobuf.GeneratedMessage
      implements ResponseReloadConfOrBuilder {
    // Use ResponseReloadConf.newBuilder() to construct.
    private ResponseReloadConf(Builder builder) {
      super(builder);
    }
    private ResponseReloadConf(boolean noInit) {}
    
    private static final ResponseReloadConf defaultInstance;
    public static ResponseReloadConf getDefaultInstance() {
      return defaultInstance;
    }
    
    public ResponseReloadConf getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return scmd.ServerCmd.internal_static_scmd_ResponseReloadConf_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return scmd.ServerCmd.internal_static_scmd_ResponseReloadConf_fieldAccessorTable;
    }
    
    private int bitField0_;
    // optional uint32 errCode = 1;
    public static final int ERRCODE_FIELD_NUMBER = 1;
    private int errCode_;
    public boolean hasErrCode() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getErrCode() {
      return errCode_;
    }
    
    private void initFields() {
      errCode_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt32(1, errCode_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, errCode_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static scmd.ServerCmd.ResponseReloadConf parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static scmd.ServerCmd.ResponseReloadConf parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static scmd.ServerCmd.ResponseReloadConf parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static scmd.ServerCmd.ResponseReloadConf parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static scmd.ServerCmd.ResponseReloadConf parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static scmd.ServerCmd.ResponseReloadConf parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static scmd.ServerCmd.ResponseReloadConf parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static scmd.ServerCmd.ResponseReloadConf parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static scmd.ServerCmd.ResponseReloadConf parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static scmd.ServerCmd.ResponseReloadConf parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(scmd.ServerCmd.ResponseReloadConf prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements scmd.ServerCmd.ResponseReloadConfOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return scmd.ServerCmd.internal_static_scmd_ResponseReloadConf_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return scmd.ServerCmd.internal_static_scmd_ResponseReloadConf_fieldAccessorTable;
      }
      
      // Construct using scmd.ServerCmd.ResponseReloadConf.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        errCode_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return scmd.ServerCmd.ResponseReloadConf.getDescriptor();
      }
      
      public scmd.ServerCmd.ResponseReloadConf getDefaultInstanceForType() {
        return scmd.ServerCmd.ResponseReloadConf.getDefaultInstance();
      }
      
      public scmd.ServerCmd.ResponseReloadConf build() {
        scmd.ServerCmd.ResponseReloadConf result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private scmd.ServerCmd.ResponseReloadConf buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        scmd.ServerCmd.ResponseReloadConf result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public scmd.ServerCmd.ResponseReloadConf buildPartial() {
        scmd.ServerCmd.ResponseReloadConf result = new scmd.ServerCmd.ResponseReloadConf(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.errCode_ = errCode_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof scmd.ServerCmd.ResponseReloadConf) {
          return mergeFrom((scmd.ServerCmd.ResponseReloadConf)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(scmd.ServerCmd.ResponseReloadConf other) {
        if (other == scmd.ServerCmd.ResponseReloadConf.getDefaultInstance()) return this;
        if (other.hasErrCode()) {
          setErrCode(other.getErrCode());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              errCode_ = input.readUInt32();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional uint32 errCode = 1;
      private int errCode_ ;
      public boolean hasErrCode() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getErrCode() {
        return errCode_;
      }
      public Builder setErrCode(int value) {
        bitField0_ |= 0x00000001;
        errCode_ = value;
        onChanged();
        return this;
      }
      public Builder clearErrCode() {
        bitField0_ = (bitField0_ & ~0x00000001);
        errCode_ = 0;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:scmd.ResponseReloadConf)
    }
    
    static {
      defaultInstance = new ResponseReloadConf(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:scmd.ResponseReloadConf)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_scmd_RequestStopServer_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_scmd_RequestStopServer_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_scmd_RequestReloadConf_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_scmd_RequestReloadConf_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_scmd_ResponseReloadConf_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_scmd_ResponseReloadConf_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017ServerCmd.proto\022\004scmd\"%\n\021RequestStopSe" +
      "rver\022\020\n\010serverId\030\001 \001(\r\"7\n\021RequestReloadC" +
      "onf\022\020\n\010serverId\030\001 \001(\r\022\020\n\010confFile\030\002 \001(\t\"" +
      "%\n\022ResponseReloadConf\022\017\n\007errCode\030\001 \001(\r"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_scmd_RequestStopServer_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_scmd_RequestStopServer_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_scmd_RequestStopServer_descriptor,
              new java.lang.String[] { "ServerId", },
              scmd.ServerCmd.RequestStopServer.class,
              scmd.ServerCmd.RequestStopServer.Builder.class);
          internal_static_scmd_RequestReloadConf_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_scmd_RequestReloadConf_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_scmd_RequestReloadConf_descriptor,
              new java.lang.String[] { "ServerId", "ConfFile", },
              scmd.ServerCmd.RequestReloadConf.class,
              scmd.ServerCmd.RequestReloadConf.Builder.class);
          internal_static_scmd_ResponseReloadConf_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_scmd_ResponseReloadConf_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_scmd_ResponseReloadConf_descriptor,
              new java.lang.String[] { "ErrCode", },
              scmd.ServerCmd.ResponseReloadConf.class,
              scmd.ServerCmd.ResponseReloadConf.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
